version: '3'
services:
    derpbot:
        build: .
        restart: unless-stopped
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
             - /docker/data/derpbot:/derpbot/config
        environment:
          - TZ=Europe/Helsinki